### ISSUE TITLE
DNS, domain, subdomain, etc... issue

### ISSUE THREAD

**Issue by arnaduga** [zoph-io/url-shortener#2]
Hi!

Maybe not a bug, but a misunderstanding from my side, but I wasn't able to instanciate the shortener...

I have a domain name registered outside of Route53. Let's name it "domain.com" (original, huh?)

I _thought_ the target would be "short.domain.com" for the companion app, and "<subdomain>.domain.com" for the shortened link (as your shortened.zoph.io".

So, I created:
- public Route 53 hosted zone for short.domain.com
- public Rotue 53 hosted zone for link.domain.com (considering link is my subdomain)
-  NS record on my domain provider to declare these 2 subdomains to be managed by Route 53
- A certificate for both subdomains (I'm not comfortable in using wildcard)

In the make file I set the values 
```
Domain := domain.com
SubDomain := link
```

But it failed to deploy when reaching teh Route53RecordSetGroup resource, with error message "No hosted zones named domain.com. found"

I'm pretty sure I missed the target domain/subdomain organisation. I wanted to keep my domain/subdomain as short as possible (otherwise, what's the point of an URL shortener): I'd like to avoid "*.short.domain.com" ....

Can you help?

**Comment by z0ph** [comment]
Hey Arnaud,

Thanks for giving a try to my shortener!

Your settings in the `Makefile` are correct. The problem is that you should have a Route53 zone corresponding to the "Domain" (naked domain) variable, but in your case, you have only `short.domain` and `link.domain`.

You have the option to migrate the domain to Route53, or maybe use another one just for shortener (a very short domain and TLD).

**Comment by arnaduga** [comment]
Thanks for your reply!

I'll migrate one of my (too) many domains to Route 53, to do it that way. Process is quite long, so, I need to wait. I'll let you know.

Another remark: I got some crash because of Python version. I updated my `backend/backend.yaml` file to update the version : 
![image](https://github.com/user-attachments/assets/40317aee-1a03-465f-b494-2491ebb7eca3)


Not the most elegant thing I've done :/ I should also install the appropriate Python version.

**Comment by z0ph** [comment]
> Thanks for your reply!
> 
> I'll migrate one of my (too) many domains to Route 53, to do it that way. Process is quite long, so, I need to wait. I'll let you know.
> 
> Another remark: I got some crash because of Python version. I updated my `backend/backend.yaml` file to update the version : ![image](https://private-user-images.githubusercontent.com/56150873/356150559-40317aee-1a03-465f-b494-2491ebb7eca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjA1NzgsIm5iZiI6MTcyMzEyMDI3OCwicGF0aCI6Ii81NjE1MDg3My8zNTYxNTA1NTktNDAzMTdhZWUtMWEwMy00NjVmLWI0OTQtMjQ5MWViYjdlY2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDEyMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYmMxZGZjMjk4NjE5NmEzNDM0MTY3YmVmNjQzODU4YzA3ZWRlZTM4MzcwOGU2NjY1NmU0MWU3MzM5N2RhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NkgKShxgBHHIktIbfy1GV4Q78eKEvnxfbo9_WBKhKhs)
> 
> Not the most elegant thing I've done :/ I should also install the appropriate Python version.

Good point, I've updated the python version too!
